export const RELATIONSHIP_TYPES = [
  { key: 'mother', label: 'Annem', domain: 'family' },
  { key: 'father', label: 'Babam', domain: 'family' },
  { key: 'sibling', label: 'Kardeşim', domain: 'family' },
  { key: 'relative', label: 'Akraba', domain: 'family' },
  { key: 'best_friend', label: 'Yakın Arkadaş', domain: 'friend' },
  { key: 'friend', label: 'Arkadaş', domain: 'friend' },
  { key: 'roommate', label: 'Ev Arkadaşı', domain: 'friend' },
  { key: 'neighbor', label: 'Komşu', domain: 'friend' },
  { key: 'crush', label: 'Hoşlandığım Kişi', domain: 'romantic' },
  { key: 'date', label: 'Flört', domain: 'romantic' },
  { key: 'partner', label: 'Sevgili/Partner', domain: 'romantic' },
  { key: 'fiance', label: 'Nişanlı', domain: 'romantic' },
  { key: 'spouse', label: 'Eş', domain: 'romantic' },
  { key: 'coworker', label: 'İş Arkadaşı', domain: 'work' },
  { key: 'manager', label: 'Yönetici', domain: 'work' },
  { key: 'direct_report', label: 'Ekip Üyem', domain: 'work' },
  { key: 'client', label: 'Müşteri', domain: 'work' },
  { key: 'vendor', label: 'Tedarikçi', domain: 'work' },
  { key: 'mentor', label: 'Mentor', domain: 'work' },
  { key: 'mentee', label: 'Menti/Öğrenci', domain: 'work' },
] as const;
